#!/usr/bin/bash
termux-setup-storage
pkg update
pkg upgrade 
pkg dist-upgrade 
pkg install root-repo 
pkg install x11-repo 
pkg install termux-api 
pkg install git 
pkg install wget 
pkg install curl 
pkg install python 
pkg install php
pkg install ruby 
pkg install mc 
pkg install zsh 
pkg install toilet 
pkg install figlet 
pkg install cloudflared 
pkg install openssh 
pkg install sshpass 
gem install lolcat
python3 -m pip install --upgrade pip
sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"
